[package]
name = "api_proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.21.1"
getter = { path = "../getter", features = ["webpki-roots"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.108"
tokio = "1.33.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
strip = true
crate-type = ["rlib", "cdylib"]
